name: machine_test_nectar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  file_picker: ^8.0.0+1
  chewie: ^1.8.1
  video_player: ^2.8.5
  audioplayers: ^6.0.0
  lottie: ^3.1.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  flutter_pdfview: ^1.3.2
  image_picker: ^1.0.8
  record: ^4.4.4
  open_file_plus: ^3.4.1+1

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
